// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"database/sql"
	"time"
)

type Item struct {
	ID          int32          `json:"id"`
	MenuID      int32          `json:"menuID"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Image       sql.NullString `json:"image"`
	Price       string         `json:"price"`
	UpdatedAt   sql.NullTime   `json:"updatedAt"`
}

type Menu struct {
	ID           int32          `json:"id"`
	RestaurantID int32          `json:"restaurantID"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	UpdatedAt    time.Time      `json:"updatedAt"`
}

type Order struct {
	ID                  int32     `json:"id"`
	RestaurantID        int32     `json:"restaurantID"`
	CustomerName        string    `json:"customerName"`
	CustomerAddress     string    `json:"customerAddress"`
	CustomerPhoneNumber string    `json:"customerPhoneNumber"`
	OrderTime           time.Time `json:"orderTime"`
}

type Payment struct {
	ID      int32  `json:"id"`
	OrderID int32  `json:"orderID"`
	Amount  string `json:"amount"`
}

type Restaurant struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	Address     string `json:"address"`
	PhoneNumber string `json:"phoneNumber"`
	Email       string `json:"email"`
}
