// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package backend

import (
	"database/sql"
)

type Item struct {
	ID          int32          `json:"id"`
	MenuID      sql.NullInt32  `json:"menuID"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	Image       sql.NullString `json:"image"`
	Price       sql.NullString `json:"price"`
	UpdatedAt   sql.NullTime   `json:"updatedAt"`
}

type Menu struct {
	ID           int32          `json:"id"`
	RestaurantID sql.NullInt32  `json:"restaurantID"`
	Name         sql.NullString `json:"name"`
	Description  sql.NullString `json:"description"`
	UpdatedAt    sql.NullTime   `json:"updatedAt"`
}

type Order struct {
	ID                  int32          `json:"id"`
	RestaurantID        sql.NullInt32  `json:"restaurantID"`
	CustomerName        sql.NullString `json:"customerName"`
	CustomerAddress     sql.NullString `json:"customerAddress"`
	CustomerPhoneNumber sql.NullString `json:"customerPhoneNumber"`
	OrderTime           sql.NullTime   `json:"orderTime"`
}

type Payment struct {
	ID      int32          `json:"id"`
	OrderID sql.NullInt32  `json:"orderID"`
	Amount  sql.NullString `json:"amount"`
}

type Restaurant struct {
	ID          int32          `json:"id"`
	Name        sql.NullString `json:"name"`
	Address     sql.NullString `json:"address"`
	PhoneNumber sql.NullString `json:"phoneNumber"`
	Email       sql.NullString `json:"email"`
}
